# compose.yaml
version: '3.8'
services:
frontend:
build:
context: ./frontend
dockerfile: Dockerfile
args: # Pass build arguments to the Dockerfile
REACT_APP_BACKEND_URL_ARG: http://localhost:80 # Frontend
connects to Nginx on port 80, which proxies /api to backend:8001
ports:
- "80:80" # Map host port 80 to container port 80 (Nginx
default)
depends_on:
- backendbackend:
build:
context: ./backend
dockerfile: Dockerfile
ports:
- "8001:8001" # Map host port 8001 to container port 8001
(FastAPI default)
depends_on:
- db
environment:
# These will be replaced by K8s Secrets later
DATABASE_URL: postgresql://user:password@db:5432/mydatabase
db:
image: postgres:13 # Use a specific version for stability
restart: always
environment:
POSTGRES_DB: mydatabase
POSTGRES_USER: user
POSTGRES_PASSWORD: password
ports:
- "5432:5432" # Optional: if you want to access DB from host
volumes:
- db_data:/var/lib/postgresql/data # Persist database data
volumes:
db_data: # Define the named volume