"""Seed the database with categories, products and an admin user."""
from database import SessionLocal, engine, Base
import models
from auth import hash_password
from sqlalchemy import text

Base.metadata.create_all(bind=engine)

def seed():
    db = SessionLocal()
    try:
        if db.query(models.User).count() > 0:
            print("DB already seeded, skipping.")
            return

        # ── Users ──────────────────────────────────────────────────────────────
        admin = models.User(name="Admin", email="admin@shop.com",
                            hashed_password=hash_password("admin123"),
                            role=models.UserRole.admin)
        demo = models.User(name="Demo User", email="demo@shop.com",
                           hashed_password=hash_password("demo123"),
                           role=models.UserRole.customer)
        db.add(admin); db.add(demo)

        # ── Categories ─────────────────────────────────────────────────────────
        cats = [
            models.Category(name="Electronics", slug="electronics",
                description="Gadgets, devices & tech accessories",
                image_url="https://images.unsplash.com/photo-1498049794561-7780e7231661?w=500"),
            models.Category(name="Apparel", slug="apparel",
                description="Clothing, shoes & fashion",
                image_url="https://images.unsplash.com/photo-1445205170230-053b83016050?w=500"),
            models.Category(name="Home & Garden", slug="home-garden",
                description="Furniture, kitchen & garden essentials",
                image_url="https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500"),
            models.Category(name="Sports", slug="sports",
                description="Sports, fitness & outdoor gear",
                image_url="https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500"),
            models.Category(name="Books", slug="books",
                description="Books, e-books & audiobooks",
                image_url="https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500"),
            models.Category(name="Beauty", slug="beauty",
                description="Skincare, makeup & personal care",
                image_url="https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500"),
            models.Category(name="Gaming", slug="gaming",
                description="Games, consoles & accessories",
                image_url="https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=500"),
            models.Category(name="Food & Grocery", slug="food-grocery",
                description="Organic, gourmet & pantry staples",
                image_url="https://images.unsplash.com/photo-1542838132-92c53300491e?w=500"),
        ]
        for c in cats:
            db.add(c)
        db.flush()

        ei = cats[0].id; ai = cats[1].id; hi = cats[2].id; si = cats[3].id
        bi = cats[4].id; bti = cats[5].id; gi = cats[6].id; fi = cats[7].id

        # ── Products ───────────────────────────────────────────────────────────
        products = [
            # ── Electronics (8) ──────────────────────────────────────────────
            models.Product(name='MacBook Pro 16"', slug="macbook-pro-16",
                description="Apple M3 Pro chip, 18GB RAM, 512GB SSD. The ultimate professional laptop.",
                price=2499.00, original_price=2799.00, category_id=ei,
                image_url="https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600",
                stock_quantity=15, is_featured=True, brand="Apple", rating=4.9, review_count=128,
                tags="laptop,apple,macbook,pro"),
            models.Product(name="Sony WH-1000XM5", slug="sony-wh-1000xm5",
                description="Industry-leading noise cancelling wireless headphones with 30hr battery.",
                price=349.99, original_price=399.99, category_id=ei,
                image_url="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
                stock_quantity=40, is_featured=True, brand="Sony", rating=4.8, review_count=89,
                tags="headphones,wireless,noise-cancelling,sony"),
            models.Product(name="iPhone 15 Pro", slug="iphone-15-pro",
                description="A17 Pro chip, titanium design, 48MP main camera with 5x optical zoom.",
                price=999.00, original_price=1099.00, category_id=ei,
                image_url="https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600",
                stock_quantity=25, is_featured=True, brand="Apple", rating=4.7, review_count=215,
                tags="iphone,smartphone,apple,5g"),
            models.Product(name='Samsung 4K OLED TV 55"', slug="samsung-oled-tv-55",
                description="Quantum OLED panel, 120Hz, HDR10+, built-in Alexa & Google Assistant.",
                price=1299.00, original_price=1599.00, category_id=ei,
                image_url="https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600",
                stock_quantity=8, brand="Samsung", rating=4.6, review_count=52,
                tags="tv,oled,samsung,4k"),
            models.Product(name="Logitech MX Master 3S", slug="logitech-mx-master-3s",
                description="Advanced wireless mouse — 8000 DPI sensor, silent clicks, USB-C.",
                price=99.99, original_price=109.99, category_id=ei,
                image_url="https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600",
                stock_quantity=60, brand="Logitech", rating=4.8, review_count=177,
                tags="mouse,wireless,logitech,ergonomic"),
            models.Product(name="iPad Pro 12.9\" M2", slug="ipad-pro-12-m2",
                description="M2 chip, Liquid Retina XDR display, Apple Pencil & Magic Keyboard support.",
                price=1099.00, original_price=1199.00, category_id=ei,
                image_url="https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600",
                stock_quantity=20, is_featured=True, brand="Apple", rating=4.8, review_count=143,
                tags="ipad,tablet,apple,m2"),
            models.Product(name="DJI Mini 4 Pro Drone", slug="dji-mini-4-pro",
                description="4K/60fps video, 3-axis gimbal, 34-min flight time, under 249g.",
                price=759.00, original_price=899.00, category_id=ei,
                image_url="https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600",
                stock_quantity=12, is_featured=True, brand="DJI", rating=4.7, review_count=64,
                tags="drone,dji,camera,aerial"),
            models.Product(name="Samsung Galaxy Watch 6", slug="samsung-galaxy-watch-6",
                description="Health tracking, BioActive sensor, sleep coaching, 40hr battery.",
                price=299.99, original_price=349.99, category_id=ei,
                image_url="https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
                stock_quantity=35, brand="Samsung", rating=4.5, review_count=88,
                tags="smartwatch,samsung,fitness,wearable"),

            # ── Apparel (6) ──────────────────────────────────────────────────
            models.Product(name="Premium Cotton Hoodie", slug="premium-cotton-hoodie",
                description="Ultra-soft 100% organic cotton, relaxed fit, kangaroo pocket. 6 colors.",
                price=59.99, original_price=79.99, category_id=ai,
                image_url="https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600",
                stock_quantity=120, is_featured=True, brand="Essentials", rating=4.7, review_count=304,
                tags="hoodie,cotton,casual,unisex"),
            models.Product(name="Slim Fit Chinos", slug="slim-fit-chinos",
                description="Stretch cotton blend, wrinkle-resistant, available in 8 colors.",
                price=49.99, category_id=ai,
                image_url="https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600",
                stock_quantity=80, brand="Essentials", rating=4.5, review_count=62,
                tags="chinos,pants,slim-fit,cotton"),
            models.Product(name="Running Sneakers", slug="running-sneakers",
                description="Breathable mesh upper, responsive foam midsole, rubber outsole. US 6–14.",
                price=89.99, original_price=110.00, category_id=ai,
                image_url="https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
                stock_quantity=95, is_featured=True, brand="SpeedRun", rating=4.6, review_count=140,
                tags="sneakers,running,shoes,sport"),
            models.Product(name="Merino Wool Sweater", slug="merino-wool-sweater",
                description="100% extra-fine Merino wool, machine washable, classic crew neck.",
                price=119.00, original_price=149.00, category_id=ai,
                image_url="https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600",
                stock_quantity=55, brand="Wool&Co", rating=4.8, review_count=97,
                tags="sweater,merino,wool,winter"),
            models.Product(name="Leather Crossbody Bag", slug="leather-crossbody-bag",
                description="Full-grain Italian leather, adjustable strap, brass hardware.",
                price=149.00, original_price=199.00, category_id=ai,
                image_url="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
                stock_quantity=38, is_featured=True, brand="ArtisanLeather", rating=4.7, review_count=72,
                tags="bag,leather,crossbody,fashion"),
            models.Product(name="Linen Summer Dress", slug="linen-summer-dress",
                description="100% natural linen, flowy midi cut, available in 5 colors.",
                price=79.99, original_price=99.99, category_id=ai,
                image_url="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600",
                stock_quantity=65, brand="SummerBloom", rating=4.6, review_count=118,
                tags="dress,linen,summer,women"),

            # ── Home & Garden (5) ────────────────────────────────────────────
            models.Product(name="Espresso Machine Pro", slug="espresso-machine-pro",
                description="15-bar pump, steam wand, double boiler, 2.5L tank. Barista quality.",
                price=349.00, original_price=449.00, category_id=hi,
                image_url="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600",
                stock_quantity=22, is_featured=True, brand="Breville", rating=4.8, review_count=93,
                tags="espresso,coffee,kitchen,breville"),
            models.Product(name="Ceramic Cookware Set 10pc", slug="ceramic-cookware-set",
                description="Non-stick ceramic, PFAS-free, oven-safe to 450°F, dishwasher safe.",
                price=199.99, original_price=249.99, category_id=hi,
                image_url="https://images.unsplash.com/photo-1584990347449-a2d4c2c044c9?w=600",
                stock_quantity=30, brand="GreenPan", rating=4.5, review_count=67,
                tags="cookware,ceramic,kitchen,nonstick"),
            models.Product(name="Smart Air Purifier", slug="smart-air-purifier",
                description="HEPA H13 filter, removes 99.97% particles, app-controlled, 500 sq ft.",
                price=229.99, original_price=279.99, category_id=hi,
                image_url="https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600",
                stock_quantity=28, brand="Dyson", rating=4.7, review_count=56,
                tags="air-purifier,hepa,dyson,smart"),
            models.Product(name="Bamboo Bedding Set Queen", slug="bamboo-bedding-set-queen",
                description="100% organic bamboo, 400 thread count, cooling & hypoallergenic.",
                price=129.99, original_price=159.99, category_id=hi,
                image_url="https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600",
                stock_quantity=44, is_featured=True, brand="Cozy Earth", rating=4.9, review_count=211,
                tags="bedding,bamboo,organic,sleep"),
            models.Product(name="Philips Hue Starter Kit", slug="philips-hue-starter-kit",
                description="4 smart LED bulbs + bridge, 16M colors, voice & app control.",
                price=149.95, original_price=179.99, category_id=hi,
                image_url="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
                stock_quantity=50, brand="Philips", rating=4.6, review_count=134,
                tags="smart-home,lights,hue,philips"),

            # ── Sports (5) ──────────────────────────────────────────────────
            models.Product(name="Yoga Mat Premium", slug="yoga-mat-premium",
                description="6mm thick, eco-friendly TPE, non-slip texture, carrying strap included.",
                price=39.99, category_id=si,
                image_url="https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=600",
                stock_quantity=150, brand="Manduka", rating=4.7, review_count=222,
                tags="yoga,mat,fitness,exercise"),
            models.Product(name="Adjustable Dumbbells 50lb", slug="adjustable-dumbbells-50lb",
                description="Fast dial adjust from 5–50 lbs, replaces 15 sets, includes storage tray.",
                price=299.99, original_price=349.99, category_id=si,
                image_url="https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600",
                stock_quantity=18, is_featured=True, brand="Bowflex", rating=4.9, review_count=189,
                tags="dumbbells,weights,fitness,bowflex"),
            models.Product(name="Garmin Forerunner 265", slug="garmin-forerunner-265",
                description="AMOLED display, GPS, HRV status, recovery advisor, 13-day battery.",
                price=449.99, original_price=499.99, category_id=si,
                image_url="https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600",
                stock_quantity=24, is_featured=True, brand="Garmin", rating=4.8, review_count=76,
                tags="garmin,gps,running,watch,fitness"),
            models.Product(name="Resistance Bands Set 11pc", slug="resistance-bands-set",
                description="5 resistance levels, door anchor, handles, ankle straps, carry bag.",
                price=29.99, original_price=44.99, category_id=si,
                image_url="https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600",
                stock_quantity=200, brand="FitLife", rating=4.6, review_count=445,
                tags="resistance-bands,workout,home-gym,fitness"),
            models.Product(name="Hydroflask 32oz Wide Mouth", slug="hydroflask-32oz",
                description="TempShield double-wall insulation, keeps cold 24hr / hot 12hr, BPA-free.",
                price=44.95, category_id=si,
                image_url="https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600",
                stock_quantity=180, brand="Hydro Flask", rating=4.8, review_count=532,
                tags="water-bottle,hydroflask,insulated,hiking"),

            # ── Books (5) ────────────────────────────────────────────────────
            models.Product(name="Atomic Habits", slug="atomic-habits",
                description="Tiny changes, remarkable results. By James Clear. #1 NYT Bestseller.",
                price=16.99, category_id=bi,
                image_url="https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600",
                stock_quantity=200, brand="Penguin", rating=4.9, review_count=512,
                tags="habits,self-help,productivity,bestseller"),
            models.Product(name="Clean Code", slug="clean-code",
                description="A handbook of agile software craftsmanship by Robert C. Martin.",
                price=42.99, category_id=bi,
                image_url="https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600",
                stock_quantity=75, brand="Prentice Hall", rating=4.7, review_count=308,
                tags="programming,software,coding,clean-code"),
            models.Product(name="The Psychology of Money", slug="psychology-of-money",
                description="Timeless lessons on wealth, greed and happiness by Morgan Housel.",
                price=18.99, category_id=bi,
                image_url="https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600",
                stock_quantity=150, is_featured=True, brand="Harriman House", rating=4.8, review_count=389,
                tags="finance,money,investing,bestseller"),
            models.Product(name="Deep Work", slug="deep-work",
                description="Rules for focused success in a distracted world by Cal Newport.",
                price=17.99, category_id=bi,
                image_url="https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600",
                stock_quantity=120, brand="Grand Central", rating=4.7, review_count=274,
                tags="productivity,focus,deep-work,cal-newport"),
            models.Product(name="System Design Interview Vol.2", slug="system-design-interview-v2",
                description="An insider's guide to system design interviews. By Alex Xu.",
                price=35.99, category_id=bi,
                image_url="https://images.unsplash.com/photo-1589998059171-988d887df646?w=600",
                stock_quantity=90, brand="ByteByteGo", rating=4.9, review_count=193,
                tags="system-design,interview,software,engineering"),

            # ── Beauty (5) ───────────────────────────────────────────────────
            models.Product(name="The Ordinary Skincare Bundle", slug="ordinary-skincare-bundle",
                description="Niacinamide 10%, Hyaluronic Acid 2%, Retinol 0.5%. Dermatologist tested.",
                price=29.99, original_price=42.00, category_id=bti,
                image_url="https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600",
                stock_quantity=180, is_featured=True, brand="The Ordinary", rating=4.8, review_count=621,
                tags="skincare,serum,niacinamide,retinol"),
            models.Product(name="Dyson Airwrap Multi-Styler", slug="dyson-airwrap-multi-styler",
                description="Curl, wave, smooth and dry with no extreme heat. 6 attachments.",
                price=599.99, original_price=649.99, category_id=bti,
                image_url="https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600",
                stock_quantity=14, is_featured=True, brand="Dyson", rating=4.7, review_count=148,
                tags="dyson,hair,styler,beauty"),
            models.Product(name="Charlotte Tilbury Pillow Talk Palette", slug="charlotte-tilbury-pillow-talk",
                description="5 versatile shades, from sheer shimmer to deep matte. Long-wear formula.",
                price=65.00, category_id=bti,
                image_url="https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600",
                stock_quantity=60, brand="Charlotte Tilbury", rating=4.8, review_count=203,
                tags="makeup,eyeshadow,palette,beauty"),
            models.Product(name="Creed Aventus Perfume 100ml", slug="creed-aventus-100ml",
                description="Iconic woody-fruity fragrance. Top notes: blackcurrant, bergamot, apple.",
                price=435.00, original_price=495.00, category_id=bti,
                image_url="https://images.unsplash.com/photo-1541643600914-78b084683702?w=600",
                stock_quantity=22, brand="Creed", rating=4.9, review_count=87,
                tags="perfume,fragrance,luxury,creed"),
            models.Product(name="Foreo Luna 4 Face Massager", slug="foreo-luna-4",
                description="T-Sonic pulsations, 16 intensities, app-connected, 1-year battery.",
                price=199.00, original_price=239.00, category_id=bti,
                image_url="https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600",
                stock_quantity=35, brand="Foreo", rating=4.6, review_count=112,
                tags="skincare,facial,foreo,beauty-device"),

            # ── Gaming (5) ───────────────────────────────────────────────────
            models.Product(name="PlayStation 5 Slim", slug="playstation-5-slim",
                description="PlayStation 5 Slim console with DualSense controller. 1TB SSD.",
                price=449.99, category_id=gi,
                image_url="https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600",
                stock_quantity=10, is_featured=True, brand="Sony", rating=4.9, review_count=342,
                tags="ps5,playstation,console,sony,gaming"),
            models.Product(name="Xbox Series X", slug="xbox-series-x",
                description="4K gaming, 120fps, 1TB SSD, backward compatible, Game Pass ready.",
                price=499.99, category_id=gi,
                image_url="https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600",
                stock_quantity=8, is_featured=True, brand="Microsoft", rating=4.8, review_count=278,
                tags="xbox,console,microsoft,gaming,4k"),
            models.Product(name="Razer DeathAdder V3 Pro", slug="razer-deathadder-v3-pro",
                description="30K DPI Focus Pro sensor, 90hr battery, 63g ultralight wireless.",
                price=149.99, original_price=169.99, category_id=gi,
                image_url="https://images.unsplash.com/photo-1527814050087-3793815479db?w=600",
                stock_quantity=55, brand="Razer", rating=4.8, review_count=156,
                tags="gaming-mouse,razer,wireless,esports"),
            models.Product(name="Nintendo Switch OLED", slug="nintendo-switch-oled",
                description="7-inch OLED screen, 64GB storage, enhanced audio, wide adjustable stand.",
                price=349.99, category_id=gi,
                image_url="https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600",
                stock_quantity=20, brand="Nintendo", rating=4.7, review_count=198,
                tags="nintendo,switch,oled,portable,gaming"),
            models.Product(name="SteelSeries Arctis Nova Pro", slug="steelseries-arctis-nova-pro",
                description="Hi-Fi audio, ANC, multi-system connect, hot-swap battery, 360° spatial.",
                price=249.99, original_price=299.99, category_id=gi,
                image_url="https://images.unsplash.com/photo-1612444491699-e8fd2e0b81a2?w=600",
                stock_quantity=30, brand="SteelSeries", rating=4.7, review_count=94,
                tags="gaming-headset,steelseries,anc,wireless"),

            # ── Food & Grocery (4) ───────────────────────────────────────────
            models.Product(name="Organic Manuka Honey 500g", slug="manuka-honey-500g",
                description="MGO 400+, UMF 13+, certified raw from New Zealand. Rich & creamy.",
                price=54.99, original_price=69.99, category_id=fi,
                image_url="https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=600",
                stock_quantity=90, is_featured=True, brand="Comvita", rating=4.9, review_count=267,
                tags="honey,manuka,organic,new-zealand"),
            models.Product(name="Premium Colombian Coffee Beans 1kg", slug="colombian-coffee-beans-1kg",
                description="Single-origin, medium roast, notes of chocolate & caramel. Whole bean.",
                price=24.99, original_price=32.99, category_id=fi,
                image_url="https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600",
                stock_quantity=160, brand="Lavazza", rating=4.8, review_count=334,
                tags="coffee,beans,colombian,medium-roast"),
            models.Product(name="Olive Oil Extra Virgin 3L", slug="olive-oil-extra-virgin-3l",
                description="Cold-pressed, Greek PDO, <0.2% acidity, polyphenol-rich, award-winning.",
                price=39.99, original_price=49.99, category_id=fi,
                image_url="https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
                stock_quantity=75, brand="Gaea", rating=4.7, review_count=152,
                tags="olive-oil,greek,extra-virgin,organic"),
            models.Product(name="Protein Powder Whey 2kg", slug="whey-protein-2kg",
                description="25g protein per serving, 5.5g BCAAs, low sugar, chocolate flavor.",
                price=59.99, original_price=74.99, category_id=fi,
                image_url="https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600",
                stock_quantity=110, brand="Optimum Nutrition", rating=4.7, review_count=421,
                tags="protein,whey,supplement,fitness,chocolate"),
        ]

        for p in products:
            db.add(p)

        db.commit()
        print(f"✅ Database seeded with {len(products)} products, 8 categories, 2 users.")
    except Exception as e:
        db.rollback()
        print(f"Seed error: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed()
